[build]
  command = "NEXT_TELEMETRY_DISABLED=1 npm run build"
  environment = { NODE_VERSION = "20" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
